source :rubygems

gem "sinatra", "1.3.3"
gem "torquebox-messaging", "2.x.incremental.1316"
gem "torquebox-cache", "2.x.incremental.1316"
gem "edn", "1.0.0"
gem "haml", "3.1.7"
gem "rest-client", "1.6.7"
